# Generated by Django 4.2.7 on 2023-11-14 08:15

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='stud_groups', to=settings.AUTH_USER_MODEL, verbose_name='Обучающиеся'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_group', to=settings.AUTH_USER_MODEL, validators=[courses.models.validate_teacher], verbose_name='Преподаватель'),
        ),
    ]
