# Generated by Django 4.2.7 on 2023-11-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_stud_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='stud_group',
            name='title',
            field=models.CharField(default='1', max_length=150, verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_staff': False}, null=True, related_name='stud_groups', to=settings.AUTH_USER_MODEL, verbose_name='Обучающиеся'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_group', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
